all: mone mtwo mthree

mone: proj2a.c
	gcc proj2a.c -o proj2a.exe -lpthread

mtwo: proj2b.c
	gcc proj2b.c -o proj2b.exe -lpthread

mthree: proj2c.c
	gcc proj2c.c -o proj2c.exe -lpthread

clean:
	rm *.exe 
